# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goidc < Formula
  desc ""
  homepage ""
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/juliendoutre/goidc/releases/download/v0.2.0/goidc_Darwin_x86_64.tar.gz"
      sha256 "b81b8cca91f9f4c2367b48597b0032adfa06b9a3a66c1b01c8b689535e4dac93"

      def install
        bin.install "goidc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/juliendoutre/goidc/releases/download/v0.2.0/goidc_Darwin_arm64.tar.gz"
      sha256 "543ae6a6eb9fd4d043c6da89c6f5fd770141f726b02c9b29f19ad8c2429d9615"

      def install
        bin.install "goidc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/juliendoutre/goidc/releases/download/v0.2.0/goidc_Linux_x86_64.tar.gz"
        sha256 "f9247510393cfc5cdce5b146109eb0a83d415c0ddd82d1048f98885915b4ea41"

        def install
          bin.install "goidc"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/juliendoutre/goidc/releases/download/v0.2.0/goidc_Linux_arm64.tar.gz"
        sha256 "592a2dd471aa9e6e7decd03ce4c51b8803c9e8255cfc4ae42dcad31d002ae7cf"

        def install
          bin.install "goidc"
        end
      end
    end
  end
end
