# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goidc < Formula
  desc ""
  homepage ""
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/juliendoutre/goidc/releases/download/v0.1.0/goidc_Darwin_x86_64.tar.gz"
      sha256 "6fdae070b891bb28364c41d34cc87a1f6c5350021a884dd87da0215876d9efe2"

      def install
        bin.install "goidc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/juliendoutre/goidc/releases/download/v0.1.0/goidc_Darwin_arm64.tar.gz"
      sha256 "a5c0ebd969c6a34cbfc8b00289f405b693c05c8db7af83f7ecf1f757c0aa3c70"

      def install
        bin.install "goidc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/juliendoutre/goidc/releases/download/v0.1.0/goidc_Linux_x86_64.tar.gz"
        sha256 "fcf6e86be5bfd36c19344752e1c234804bc69975ae151a866a0e60b02d656904"

        def install
          bin.install "goidc"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/juliendoutre/goidc/releases/download/v0.1.0/goidc_Linux_arm64.tar.gz"
        sha256 "18f0863848a6917335e08880dde06e7b8bc49110a12aaa31d67c9fc2137f9597"

        def install
          bin.install "goidc"
        end
      end
    end
  end
end
